### ISSUE TITLE
Fira font package

### ISSUE THREAD

**Issue by andymikulski** [FirefoxUX/design-tokens#13]
According to https://github.com/mozilla/Fira/issues/210#issuecomment-315509350, the Fira font used for Photon has been relocated to [carrois/Fira](https://github.com/carrois/Fira). This repo has all the proper webfont files, but does _not_ offer an NPM package to import Fira from.

Should the `Fira` webfont files exist in the `design-tokens` repo? On the one hand, it makes sense to house all of the necessary files here, but an argument could be made to submit a PR to carrois/Fira. Ideally we would have some sort of `photon-fonts` package, and I suspect that would be easier to manage if we wrapped all the files into `design-tokens`.

Currently, we can simply rely on the CDN's [fira.css](https://code.cdn.mozilla.net/fonts/fira.css) through `@import`s, but that seems less than stellar.

**Comment by aminalhazwani** [comment]
We are discussing if we should continue to use Fira on the web instead of simply using system fonts. So for the time being we are going to close this issue.
