### ISSUE TITLE
Have CSS variables for more stuff

### ISSUE THREAD

**Issue by julienw** [FirefoxUX/design-tokens#15]
Things that come to my mind:
* transitions: the bezier curve, the possible durations
* shadows

**Comment by vanillajonathan** [comment]
Currently all files are auto-generated with data from the `photon.json` file which just consists of colors.

For a more comphrensive style sheet see pull request #10.

**Comment by aminalhazwani** [comment]
Yes, in our long-term plan we are going to have multiple tokens for multiple design decision. For now we have icons and colors, see the new repos:
- https://github.com/FirefoxUX/photon-icons
- https://github.com/FirefoxUX/photon-colors
