### ISSUE TITLE
Ship photon-colors.css with Firefox

### ISSUE THREAD

**Issue by vanillajonathan** [FirefoxUX/design-tokens#21]
Ship the `photon-colors.css` style sheet with Firefox, reachable through the `chrome://` URI.

This allows Firefox to internally make use of the design tokens.
It also allows third-party WebExtension developers to reference the style sheet directly without redundantly bundling the style sheet with every WebExtension.

**Comment by aminalhazwani** [comment]
hey @vanillajonathan see related comment here https://github.com/FirefoxUX/design-tokens/pull/10#issuecomment-339592991 :)

**Comment by aminalhazwani** [comment]
Hey @vanillajonathan this is a great idea, we moved the photon-colors to a new repo https://github.com/FirefoxUX/photon-colors so we are going to close this issue and move it to the new repo, thanks!

**Comment by vanillajonathan** [comment]
The new issue in the new repository is at: https://github.com/FirefoxUX/photon-colors/issues/2
