### ISSUE TITLE
Minor updates on GIMP color palette

### ISSUE THREAD

**Issue by aminalhazwani** [FirefoxUX/design-tokens#26]
Hey @vanillajonathan I was testing the Gimp Palette on both macOS and Ubuntu and when imported the palette name is set to "colors.gpl". Do you know if it's possible to set it to "Photon Colors"? (I am also in the process of changing the other generated files to photon-colors.ext)

<img width="631" alt="screen shot 2017-11-17 at 12 07 29 pm" src="https://user-images.githubusercontent.com/1721875/32944464-efa74bf6-cb8f-11e7-8936-5f3ee301b057.png">

When using the tokens in applications I would like to suggest if possible to name them "Magenta 50" instead "magenta-50". Can you help on that? 

<img width="426" alt="screen shot 2017-11-17 at 12 06 46 pm" src="https://user-images.githubusercontent.com/1721875/32944562-42eaa40c-cb90-11e7-8f67-48596c40d9ce.png">

**Comment by vanillajonathan** [comment]
Looking at GPL palette files my understanding is that the first line should be `GIMP Palette`, followed by `Name: the_name_here` on the second line.

See a palette file in the GIMP repository as an example:
https://github.com/GNOME/gimp/blob/master/data/palettes/Default.gpl

**Comment by vanillajonathan** [comment]
The files in the repository needs to be regenerated so the .gpl file can be updated.
