### ISSUE TITLE
Update colors readme

### ISSUE THREAD

**Issue by aminalhazwani** [FirefoxUX/design-tokens#28]
- [ ] usage in development and apps
- [ ] naming and organisation
- [ ] contribution guideline

**Comment by vanillajonathan** [comment]
Photon in GitHub-flavored markdown?

| Color |  50 | 60 | 70 | 80 | 90 |
| ----- |  -- | -- | -- | -- | -- |
| Magenta | `#ff1ad9` | `#ed00b5` | `#b5007f` | `#7d004f` | `#440027` | 
| Purple | `#9400ff` | `#8000d7` | `#6200a4` | `#440071` | `#25003e` | 
| Blue | `#45a1ff` | `#0a84ff` | `#0060df` | `#003eaa` | `#002275` | `#000f40` | 
| Teal | `#00feff` | `#00c8d7` | `#008ea4` | `#005a71` | `#002d3e` |
| Green | `#30e60b` | `#12bc00` | `#058b00` | `#006504` | `#003706` | 
| Yellow | `#ffe900` | `#d7b600` | `#a47f00` | `#715100` | `#3e2800` | 
| Red | `#ff0039` | `#d70022` | `#a4000f` | `#5a0002` | `#3e0200` |
| Orange | `#ff9400` | `#d76e00` | `#a44900` | `#712b00` | `#3e1300` |
| Grey | `#b1b1b3` | `#737373` | `#4a4a4f` | `#38383d` | `#2a2a2e` | `#0c0c0d` |
| Ink | | | `#363959` | `#202340` | `#0f1126` |
