### ISSUE TITLE
How are we going to distribute the tokens to various projects?

### ISSUE THREAD

**Issue by bwinton** [FirefoxUX/design-tokens#40]
We've got npm packages for web, but what should we do for Firefox Desktop, Android, and iOS?
A gh-pages site with zip files for download maybe? Should we also offer this for web?

**Comment by aminalhazwani** [comment]
I think we can move this issue to the specific tokens repository to have a more contextualized conversation. We started some conversations with Android engineers on how we could let them import the colors and tokens but we would need more help on their side in order to make this happen.
