### ISSUE TITLE
There are no icons in the icons folders :(

### ISSUE THREAD

**Issue by johngruen** [FirefoxUX/design-tokens#45]
well, there's an info icon, but that's it

**Comment by aminalhazwani** [comment]
Yeah, they are on their way 🙂 in the meantime please refer to this one http://design.firefox.com/icons/

**Comment by johngruen** [comment]
i know, i just wanna grab them all at once!

**Comment by aminalhazwani** [comment]
Ok, we started working on this, see #48. Downloading them all is not something that we would recommend as you would then miss on future updates nevertheless I would like to hear more on why you would prefer to grab them all at once, can you share the scenario with us @johngruen?

**Comment by johngruen** [comment]
Sometimes i need five or six icons at a time...would be nice to just generate a download bundle or something.

**Comment by aminalhazwani** [comment]
Check the new repo https://github.com/FirefoxUX/photon-icons where you can pull all the icons with the NPM module
